### ISSUE TITLE
Naming (labeling) of uploads on /files page

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#1444]
- [ ] Update /files to allow user ability to add a "name" to their uploads that displays in a column titled "Upload Name" in their UI list. (Similar in functionality to web3's "Name").
- [ ] add tooltip to column header saying "An optional text label for identifying your uploads"
- [ ] Uploading will use the file name as the default label that's displayed in this field.
- [ ] Enable users to edit the names of their uploads (same functionality as Web3 uploaded files). 

## Rough wire to show implementation (note, mock missing ability for user to edit name, thus may need edit icon similar to web3)
![Screen Shot 2022-06-10 at 9 34 58 AM](https://user-images.githubusercontent.com/2078567/173089024-40aa0675-be17-4610-9952-a4c141cf9fe6.png)

## Original Request:
A collab requested that we be able to add labels to uploads (similar to how it's done on Web3.Storage) so they could remember what upload corresponds to what

* Note, this label is only needed by nft.storage in the webUI to help user organize uploads. 
(Note, somewhat related to #719 but that shouldnt block this feature)

**Comment by JeffLowe** [comment]
Currently, web3 uses the name of the file uploaded as the default name (or label) of the upload (as seen in the UI): 
<img width="754" alt="Screen Shot 2022-02-24 at 8 48 03 AM" src="https://user-images.githubusercontent.com/2078567/155547257-9edcb6c3-8f9d-4317-8946-9019926cf761.png">

This "name" label can be edited after the upload in the UI, but does not change the name of the file that was uploaded.  

@dchoi27 To confirm, we are wanting the same kind of UI functionality for nft.storage as described above? 

Suggestion:  We should either add a tooltip to this new column to ensure users understand it's a "label for their upload", or perhaps rename the column to be "Upload Label" or just "Label"

**Comment by dchoi27** [comment]
Some thoughts:
- You obviously know this, but stating because important - there's no way to change the name of the file that was uploaded (would change the CID)
- The default upload in Web3.Storage actually wraps the file in a directory, so filename does end up getting preserved (it becomes the only file in the directory, and you access it via `rootCid/filename` (here's an example from my account: https://bafybeicazdlzs3ku7xxjqx55bvepzrntjojysoxs4mzq5ph67yhmycmzqe.ipfs.dweb.link/)
- I think in this case, we obviously don't want to wrap in a directory, but just give them a label that means something only in the context of NFT.Storage. Having this editable only in the WebUI (at least at first) makes sense to me

I think what you're saying is basically aligned with this, minus the fact that it works the same as in Web3.Storage

**Comment by JeffLowe** [comment]
@dchoi27  Does it make sense to use "Upload Tag" as the column header?  We could make it "name" but that seems sort of misleading, since it's truly only a label or tag identifying the upload for user. 
Tooltip in the column header could be:  "An optional text tag for organizing your uploads"

Also, I recorded this related feature https://github.com/nftstorage/nft.storage/issues/1469 as something possibly needed by users (particularly ones needing to find particularly labeled uploads)

**Comment by dchoi27** [comment]
Good call-out, though I don't think Tag is ideal either, since it has a connotation with a certain set of expectations (multiple tags per upload, shared tags, filter by tag). I think Label is better?

**Comment by JeffLowe** [comment]
@cmunns design thoughts here?

**Comment by cmunns** [comment]
My 2 cents here is that tag ( I agree with David ) does infer additional organizational benefit and interaction, however if we are expecting the user to group shared uploads by similar tags for search it makes total sense especially if they are shorter in length e.g. 'nft-proj-1', 'nft-proj-2', etc. However, If this field is going to be longer and most of the time unique without sorting required "Label (optional)" makes more sense. The optional in the header column would be likely be enough to indicate to the user it's an internal value.

**Comment by dchoi27** [comment]
OK let's go with Label!

**Comment by jchris** [comment]
@mikeal should we remove this from web3 also? I used this data model to show why it doesn't belong. I think we are aligned here but please check my work

<img width="1105" alt="Screen Shot 2022-04-20 at 11 17 01 AM" src="https://user-images.githubusercontent.com/253/164296336-4e797049-f112-4600-b136-324c173bf000.png">
.

**Comment by JeffLowe** [comment]
For reference, the "name" of an upload (which defaults to filename, but user allowed to change value) as seen on current Web3 UI
![Screen Shot 2022-04-20 at 1 28 09 PM](https://user-images.githubusercontent.com/2078567/164298273-86a54470-07ea-466b-9d8f-67e1c61839cc.png)

**Comment by dchoi27** [comment]
I think people actually use this in Web3.Storage, so might be rough to remove. At one point I know we were still saying we'd have an uploads table associated with each NFT.Storage and Web3.Storage (alongside the uploads v2 table) - is that no longer the case?

**Comment by jchris** [comment]
I'm basing this on my understanding from a conversation with @mikeal -- the way I think about it, is that this information should encoded in the CID so it is not centralized. There is a logical place for uploads to have a label, but that is risky because the uploaded CID should not have an external label.

**Comment by dchoi27** [comment]
Makes sense - yeah let's chat about it. For the current labeling use cases I know about, it would be bad UX if changing the label changed the CID - I think labeling at the time of upload might be an intersecting but sometimes separate use case.

**Comment by JeffLowe** [comment]
Based on meeting discussions, scope refined to the following (below).  @mikeal and @Gozala need to confirm this approach before we proceed any further. 

## Tasks
- [ ] Update nft.storage /files to allow user ability to add a "name" to their uploads that displays in a column titled "Upload Name" in their UI list. (Similar in functionality to web3's "Name").
- [ ] add tooltip to column header saying "An optional text label for identifying your uploads"
- [ ] Uploading will use the file name as the default label that's displayed in this field.
- [ ] Enable users to edit the names of their uploads (same functionality as Web3 uploaded files). 


## Rough wire to show implementation (note, mock missing ability for user to edit name, thus may need edit icon similar to web3)
![Screen Shot 2022-06-10 at 9 34 58 AM](https://user-images.githubusercontent.com/2078567/173089024-40aa0675-be17-4610-9952-a4c141cf9fe6.png)

**Comment by JeffLowe** [comment]
Since the new uploads v2 work will replace current upload APIs, it's best to implement this once that lands.  Closing this out, since that need is already reflected in the active uploads v2 initiative work.
