### ISSUE TITLE
Use 🛻 pickup to handle pinning service requests

### ISSUE THREAD

**Issue by olizilla** [nftstorage/nft.storage#2309]
Review the api env, db schema, and cron jobs to find out what needs to be updated to have the api use pickup to handle pinning service requests.

## TODO

- [x] update `api/src/routes/pins-add.js` to specify ElasticIpfs as the service when calling createUpload
- [x] update `api/src/routes/pins-replace.js` to specify ElasticIpfs as the service when calling createUpload
- [x] update `cron/src/bin/pins.js` to add a cluster client configured to hit `pickup`.
- [x] update `cron/src/jobs/pins.js` to add `ElasticIpfs` to the list of Clusters to check
- [x] update `cron/src/bin/pins.js` to add a check pin statuses on pickup for via status.all
- [ ] add `staging` worker env var for `CLUSTER_API_URL` set to staging pickup url
- [ ] remove `staging` worker env var for `CLUSTER_SERVICE`
- [ ] add `prod` worker env var for `CLUSTER_API_URL` set to prod pickup url
- [ ] remove `prod` worker env var for `CLUSTER_SERVICE`

note: the env var `CLUSTER_SERVICE` takes precedence over `CLUSTER_API_URL`, so we can add a value for `CLUSTER_API_URL` whenever we like, and then delete the `CLUSTER_SERVICE` env var when we are ready for to make the switch.

Parent: https://github.com/web3-storage/pickup/issues/68

**Comment by olizilla** [comment]
Either `CLUSTER_SERVICE` or `CLUSTER_API_URL` is set in the env. 

https://github.com/nftstorage/nft.storage/blob/69a49cede3f24d723582b239596eb714b178a99d/packages/api/src/config.js#L39-L49

`CLUSTER_SERVICE` takes precedence and is a magic string that is used to select a one of a hard-coded list of cluster urls

https://github.com/nftstorage/nft.storage/blob/69a49cede3f24d723582b239596eb714b178a99d/packages/api/src/config.js#L16-L20

**Comment by olizilla** [comment]
the cloudflare dasboard shows that only `CLUSTER_SERVICE` is set in the production env for the nft.storage api worker.

**Comment by olizilla** [comment]
The `CLUSTER_API_URL` is set as a pass through url in the api router. I understand this to mean if the api worker is invoked with a request url that matches the cluster api, it will leave it alone and let the request carry on to the upstream.

https://github.com/nftstorage/nft.storage/blob/69a49cede3f24d723582b239596eb714b178a99d/packages/api/src/utils/router.js#L185-L191

I believe this is only relevant for testing, where multiple services are running on the same host.

**Comment by olizilla** [comment]
`pin-add.js` calls `db.createUpload` without specifying the service (the short name for cluster is it pinned on) or the pin status

https://github.com/nftstorage/nft.storage/blob/69a49cede3f24d723582b239596eb714b178a99d/packages/api/src/routes/pins-add.js/#L53-L54

therefore the service will be defaulted to `IpfsCluster3` per:

https://github.com/nftstorage/nft.storage/blob/69a49cede3f24d723582b239596eb714b178a99d/packages/api/src/utils/db-client.js/#L289-L302

**Comment by olizilla** [comment]
`toPinsResponse` in `db-transforms.js` is called from all the pins-* operations, and includes `delegates` that are set from the cluster lib

https://github.com/nftstorage/nft.storage/blob/69a49cede3f24d723582b239596eb714b178a99d/packages/api/src/utils/db-transforms.js#L48-L60

but this is currently stubbed out, so is not an issue. ~~We could optionally set that to be the multiaddr for e-ipfs.~~ nope, if anything that should be a pickup kubo node, but that info is not exposed yet.

https://github.com/nftstorage/nft.storage/blob/69a49cede3f24d723582b239596eb714b178a99d/packages/api/src/cluster.js#L101-L103

**Comment by olizilla** [comment]
Need to check ElasticIpfs pin statuses in cron job
https://github.com/nftstorage/nft.storage/blob/69a49cede3f24d723582b239596eb714b178a99d/packages/cron/src/jobs/pins.js#L11

**Comment by olizilla** [comment]
Update cron pins bin to pass in `pickup` cluster config

https://github.com/nftstorage/nft.storage/blob/69a49cede3f24d723582b239596eb714b178a99d/packages/cron/src/bin/pins.js#L18-L22

...and query that from the job

https://github.com/nftstorage/nft.storage/blob/69a49cede3f24d723582b239596eb714b178a99d/packages/cron/src/jobs/pins.js#L183-L185
