### ISSUE TITLE
Move NFT.Storage JS client docs to nft.storage subroute /docs

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#507]
## Overview
Right now the JS client docs are a Github page: https://ipfs-shipyard.github.io/nft.storage/client/
It's extra confusing because the nft.storage repo is in IPFS Shipyard. Let's move it to an nft.storage domain.

## Tasks
- [ ] Move all docs to /docs subroute 
- [ ] Header state is retained (same top nav with active page indicated)
- [ ] Ensure auth is shared / accessible in docs

**Comment by JeffLowe** [comment]
Just to confirm what we are needing here, 

We want this https://nftstorage.github.io/nft.storage/client/ 
to appear as a subpage of this site https://nft.storage/

If that is accurate, then a few clarifying questions:
* Are you just wanting dns updated so that https://nftstorage.github.io/nft.storage/client/ maps to something like https://nft.storage/docs (or similar)?  
* Then, the anchor nav link "Docs" on https://nft.storage/ changed to point to this route?

**Comment by dchoi27** [comment]
Yup, exactly. Just adjusting DNS sounds good to me, but @alanshaw @yusefnapora chime in if there's anything else to consider.

**Comment by JeffLowe** [comment]
@dchoi27 who has access to the registrar for nft.storage?  We'll need to make some adjustments as part of this solution.

**Comment by dchoi27** [comment]
Protocol Labs IT - if you dump some thoughts here @andyschwab can help out

**Comment by andyschwab** [comment]
Option: what do you think about having the docs portion appear at http://docs.nft.storage? This _should_ be a 5 minute update.

**Comment by dchoi27** [comment]
yup that works! then we can do /js-client and /api for https://nftstorage.github.io/nft.storage/client/ and https://nft.storage/api-docs/
