### ISSUE TITLE
NFT & web3 teams should be able to block activity from individual keys

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#606]
Both the NFT.Storage team and the web3 team might need to block user(s) if their behavior is affecting the whole system or if they are doing something malicious. We need a simple way to block a user's individual key to begin with. 

## Tasks
- [x] build out UI
- [x] House admin codebase in nft.storage github org
- [x] default landing state of app doesnt need to show list of users, only search. 
~~[ ] just use the built in "CloudFlare Access" magiclink auth provider (enter email, emails one use code)~~
- No auth, thus no login / logout button required. 
- [ ] Use existing DBs in Web3 and nft.storage with new table for storing blocked reasons, time stamps, deleted at.  
- [ ] deploy with vercel & next app (Hugo handling deployments)
- [x] display User ID and not Username (since people can signup with no user name, using email only)

## AC:

- [x]  admin user searches for token/key to find key
- [x]  admin can block an individual user's key 
- [x]  admin can unblock an individual user's key
- [x]  blocking a key requires short text note to document reason for block
- [x]  User with banned key can still log into UI

Sister issue to https://github.com/web3-storage/web3.storage/issues/536

**Comment by dchoi27** [comment]
Yeah great idea! Added

**Comment by JeffLowe** [comment]
Note: Initial implementation on Web3 side is to block individual keys, not users.  User blocking will come in future iterations.  Posting here to keep initiatives in sync.

**Comment by JeffLowe** [comment]
https://github.com/nftstorage/admin.storage/pull/1 first PR.  
With Hugo's addition of Cloudflare teams, we can start connection to that.

**Comment by JeffLowe** [comment]
Joe coordinating with Hugo on prod deployment in vercel & prod db integration

**Comment by JeffLowe** [comment]
porting ot web3 via https://github.com/web3-storage/web3.storage/pull/947
