### ISSUE TITLE
Dedicated NFT.Storage docs website

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#794]
It's about time we had a dedicated docs website for NFT.Storage.

The docs tree should include:
- Welcome page (with a quickstart, including prescriptive instructions on how to properly use IPFS URL in smart contract)
- How-tos (including how to use JS client to store metadata, how to store 
- NFT Concepts and Tutorials (link out to NFT School)
- Troubleshooting
- Reference (with links to JS client and API docs)

Issues (TODO: create issues for these):
- [ ] Design for docs website
- [x] #507
- [x] Implement website
- [x] Welcome page: Intro and quickstart that's the same as what's currently on the homepage)
- [x]  #796 (can make the How-To section and split into 3 pages)
- [ ]  Troubleshooting (move questions from FAQ)
- [ ]  NFT Concepts and Tutorials page linking to NFT School and discussing the content covered there (importance of CIDs, tutorials for various chains, etc.)

**Comment by dchoi27** [comment]
@yusefnapora can we also add a list of NFT.Storage peer IDs to the docs? Submitted a PR to IPFS docs here but we should have our own list as well so we're not bottlenecked on them merging updates: https://github.com/ipfs/ipfs-docs/pull/987

**Comment by JeffLowe** [comment]
@dchoi27 on these remaining two tasks on this epic:
1.  Troubleshooting (move questions from FAQ)
 Q: Is the need here to move all content from FAQ page and place into the troubleshooting section of the docs?
 
 2. NFT Concepts and Tutorials page linking to NFT School and discussing the content covered there (importance of CIDs, tutorials for various chains, etc.)
 Q: Is this already covered in the existing "Concepts" and "How To" sections of current docs?  Or, is this calling for additional content to be added to these sections?
 
 If anything is needed on these, reply here and I can get them tasked out separately so we can close this epic out

**Comment by dchoi27** [comment]
Thanks @JeffLowe! Before opening new issues, let's confirm with @yusefnapora on what's left

@yusefnapora do you think we need to link to NFT School for Concepts? Maybe just to some of the tutorials in an "Additional Resources" page (where we can also share general IPFS/ Filecoin resources, the Decentralizing NFT.Storage and Storage Layer Maximalism blog posts, etc.)? And not sure if we added the peer IDs anywhere (I didn't see them) but we can also add a link to those (https://github.com/nftstorage/nft.storage/issues/794#issuecomment-1004205027)

I think @yusefnapora might already have taken care of the FAQ stuff, but LMK if not
