### ISSUE TITLE
NFT.Storage gateway cache MVP

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#823]
We want to provide users with an HTTP endpoint that can fetch any data off the public IPFS network, but be super performant with NFT.Storage data in particular.

The current work plan consists on:

- [x] gateway.nft.storage naive implementation https://github.com/nftstorage/nft.storage/issues/867
- [x] setup Pinata gateway https://github.com/nftstorage/nft.storage/issues/869
- [x] gateway race with ipfs.io + CF + Pinata https://github.com/nftstorage/nft.storage/issues/868
- [x] setup logtail https://github.com/nftstorage/nft.storage/issues/1036
- [x] setup first Cache layer - CF caching on http request - validation - nftstorage/nft.storage#1180 +  nftstorage/nft.storage#1181
- [x] track and prevent rate limiting on IPFS public gateways https://github.com/nftstorage/nft.storage/issues/1165 
- [x] load test with gateway logs https://github.com/nftstorage/nft.storage/issues/870
- [x] `/ipfs/` route to gateway `nft.storage/ipfs/<cid>` (just a redirect) https://github.com/nftstorage/nft.storage/issues/1049
- [x] Setup rate limit on CF Worker https://github.com/nftstorage/nft.storage/issues/1196
- [x] Get 2-5 users to sign up for testing
- [x] **Public Launch 🎉**

Further plans on the pipeline:
- [x] Website and client with Gateway domain URL https://github.com/nftstorage/nft.storage/issues/1345
- [ ] Track wether requested content is stored in DB nftstorage/nftstorage.link#14
  - [ ] Have cache in API check https://github.com/nftstorage/nft.storage/pull/1391
- [ ] Augment gateway metrics nftstorage/nftstorage.link#18
- [ ] Add all nice metrics to Grafana
- [ ] Improve rate limit on the integrated public gateways https://github.com/nftstorage/nft.storage/issues/1195
- [ ] (should have rate limit improvements in place) warm cache + async gateway read test https://github.com/nftstorage/nft.storage/issues/755
- [ ] (should have rate limit improvements in place) async gateway read test alerts on performance degradation https://github.com/nftstorage/nft.storage/issues/871

Other ideas:
- [ ] Setup second Cache layer
  - Consider S3 with "complete" metadata flag
- [ ] add S3 as gateway alternative
- [ ] Analyze logs and optimize caching based on user patterns
- [ ] CID blocklist (+ potentially integrate with abuse (at) ipfs.io)
- [ ] Investigate sharding for partners
- [ ] Expand async gateway read test from multiple locations
- [ ] Advanced cache logic layer extensions
  - image resizing/compression
  - CBOR support for IPNFT
  - ...
- [ ] Add more gateways (Infura, Cloudflare, etc.)
- [ ] No-code API to resolve centralized URLs to CIDs https://github.com/nftstorage/nft.storage/issues/1435

More notes: https://hackmd.io/@DzQs_KK1RBK4_lT36FeM0g/H11PUd7YY

**Comment by dchoi27** [comment]
@vasco-santos do we need to ticket hooking this up to Logtail? or is that already captured somewhere

**Comment by vasco-santos** [comment]
I will add a task do hooking this with Logtail. Hopefully it is fast and easy, but given I am lacking context I will add it.
