### ISSUE TITLE
Extended admin.storage features

### ISSUE THREAD

**Issue by JeffLowe** [nftstorage/nft.storage#827]
## API key blocking additions
- [ ] when users with blocked keys use API they get specific error message instead of generic message
- [ ] Ability for admin to ban all keys for the user 

## Enable management of pinning service whitelist 
- [ ] ability to add user to allowlist for pinning api (see https://github.com/nftstorage/nft.storage/pull/1013 & https://github.com/nftstorage/nft.storage/issues/148#event-5845331853 as framework for how to accomplish) (and see https://github.com/nftstorage/nft.storage/issues/1011#issuecomment-1004503570 for discussion on rationale behind this)

## banning a user
- [ ] Ability for admin to ban a user 
- [ ] Banning a user restricts user from creating another api key (displays custom error message)
- [ ] Banning user still allows user to log into application UI 
- [ ] - Users can still log in but get a message explaining the issue, and to reach out to support@ if we haven't already reached out

## Selectors for app and functionality
- [ ] Ability in admin UI to select the "Application" context (Dropdown selector for choosing “app”:  nft.storage, web3.storage)
- [ ] Ability in admin UI to select the "Functionality" context (options depend on app selected, possible ones include so far: token, user, pinning whitelist)

## only for Web3.Storage:
- [ ] Manage web3 user data limits (connect with Agency Undone on this per their designs) (investigate enforcement on backend & update)
- [ ] Integrate with Pinning Service API allowlist and manage permission (tracking separately because Web3.Storage implementation will probably look slightly different)
- [ ] Have a way for NFT.Storage team members to trigger this block in a way that doesn't risk inadvertent mistakes (e.g., admin area)

**Comment by JeffLowe** [comment]
ported this and tasks to admin repo https://github.com/nftstorage/admin.storage/issues/9
