### ISSUE TITLE
Signed uploads w/ UCAN

### ISSUE THREAD

**Issue by dchoi27** [nftstorage/nft.storage#851]
### Design

- [x] #884
- [x] #885
- [x] #886
- [x] #1200

### Engineering
Repo: https://github.com/nftstorage/ucan.storage

- [x] #1201
- [x] #1276
- [x] #1411
- [x] Add API support for users to input DIDs
- [x]  CLI wrapper for the SDK

### Release

- [x]  Release SDK to the public
- [x]  Release API with UCAN support
- [x]  Release CLI

### Docs
- [x] #1431

### Next
ucan.storage issues here https://github.com/nftstorage/ucan.storage/issues

- [ ] #1604
- [ ] UCAN revocation (DID, specific UCAN ? )
- [ ] API: actually integrate UCAN resource pointer in the service
- [ ] Metamask signing intermediary UCAN
- [ ] #1554
- [ ] #1605
- [ ] #1616
